[project]
name = "evaluation-engine"
version = "3.0.0"
description = "drowsy_detection algorithm evaluation engine with markdown reporting"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.2",
    "pyyaml>=6.0.2",
]
